name: Vaccine Dataset Update
on:
    push:
        branches:
            - main
            - gh-pages
    schedule:
        - cron: '0 0 * * *'

jobs:
    update-datasets:
        name: Scrape and Update
        runs-on: ubuntu-latest
        steps:
            - name: Checkout own repo
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: python -m pip install -r requirements.txt

            - name: Run Scripts
              working-directory: ${{ github.workspace }}
              run: |
                    export PYTHONDONTWRITEBYTECODE=1
                    python owd_util.py
                    python nyt_util.py
                    # python chart_util.py
                    git add .
                    git status
                    git diff-index --quiet HEAD --
                    echo $?
                    # git diff --quiet
                    # echo $?

            - name: Setup Git Environment
              run: |
                    git config --global user.email "${{ github.actor }}@users.noreply.github.com"
                    git config --global user.name "${{ github.actor }}"
                    git config --global alias.switchoc '!f() { git checkout $1 2>/dev/null || git checkout -b $1; }; f'

            - name: Check for changes
              run: |
                    if git diff-index --quiet HEAD --; then
                        echo "changes_exist=true" >> $GITHUB_ENV
                    else
                        echo "changes_exist=false" >> $GITHUB_ENV
                    fi

            - name: Debug changes
              run: |
                    echo "${{ env.changes_exist }}"

            - name: Commit Datasets
              if: env.changes_exist == 'true'
              run: |
                    git commit -m "updating datasets"
                    git push

            - name: Make gh-pages branch and commit
              run: |
                    git switchoc gh-pages
                    python chart_util.py
                    git add -f index.html
                    git commit -m "updating charts"
                    git rm -rf .
                    git checkout HEAD -- index.html
                    git add .
                    git commit -m "deleting files from main"
                    git push -u -f origin gh-pages




    # publish-chart: